name: asciidoc
on:
  push:
    branches:
      - Migration_guide_files
  schedule:
    - cron:  '0 4 * * *'
jobs:
  Test:
    name: Build asciidoc
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.jdk }}
      - name: Render asciidoc
        run: mvn generate-resources
